### ISSUE TITLE
After stopping, app still asks for bluetooth to be switched on

### ISSUE THREAD

**Issue by vliedel** [dobots/presence-app#7]

**Comment by eggerdo** [comment]
yes that's true, stopping does not kill the service and the service will
notice if you turn off bluetooth and give a notification that we need
bluetooth. but if you dismiss the notification it should not show up again.
I will address this though.

**Comment by eggerdo** [comment]
Fixed in version 0.2.5: will only create a notification if scanning. no notification if bluetooth is switched off after stopping.
